version: '3.8'

services:
  cybersecurity-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - PYTHONPATH=/app